add first workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,1 +1,20 @@
+name: 01 - Building Blocks
+on: push
+    workflow_dispatch
 
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps: 
+      - name: say Hello
+        run: echo "Hello, world!"
+
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps: 
+      - name: Failed Step
+        run: |
+        echo "I will fail"
+        exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
